name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 185.180.206.46
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/latelierby-landing
            git pull origin main
